
export const myProjects = [
  {
    id: 1,
    title: "Leon Website",
    cetegory: "CSS & HTML",
    img: "/images/main/a.png",
    giturl: "https://github.com/tayseer2/HTML---CSS-Leon-Website",
    demo: "https://tayseer2.github.io/HTML---CSS-Leon-Website/",
    description: "A sleek, responsive static website design built with pure HTML and CSS.",
  },
  {
    id: 2,
    title: "Kasper Website",
    cetegory: "CSS & HTML",
    img: "/images/main/s.png",
    giturl: "https://github.com/tayseer2/HTML-And-CSS-Kasper-Website-Design",
    demo: "https://tayseer2.github.io/HTML-And-CSS-Kasper-Website-Design/",
    description: "Modern, creative website showcasing design skills using HTML and CSS.",
  },
  {
    id: 3,
    title: "Elrahhal",
    cetegory: "CSS & HTML",
    img: "/images/main/d.png",
    giturl: "https://github.com/tayseer2/HTML-And-CSS-Elrahhal",
    demo: "https://tayseer2.github.io/HTML-And-CSS-Elrahhal/",
    description: "A travel-themed website, meticulously crafted with foundational HTML and CSS.",
  },
  {
    id: 5,
    title: "QR Code Generator",
    cetegory: "JavaScript",
    img: "/images/main/g.png",
    giturl: "https://github.com/tayseer2/QR-Code-Generator",
    demo: "https://tayseer2.github.io/QR-Code-Generator/",
    description: "Generates QR codes instantly from user input using JavaScript.",
  },
  {
    id: 6,
    title: "Stop Watch",
    cetegory: "JavaScript",
    img: "/images/main/h.png",
    giturl: "https://github.com/tayseer2/stop-watch",
    demo: "https://tayseer2.github.io/stop-watch/",
    description: "A functional stopwatch application built with precise JavaScript timing.",
  },
  {
    id: 7,
    title: "Password Generator",
    cetegory: "JavaScript",
    img: "/images/main/j.png",
    giturl: "https://github.com/tayseer2/Generate-a-Random-Password",
    demo: "https://tayseer2.github.io/Generate-a-Random-Password/",
    description: "Creates strong, random passwords with customizable options using JavaScript.",
  },
  {
    id: 8,
    title: "Weather App",
    cetegory: "JavaScript",
    img: "/images/main/k.png",
    giturl: "https://github.com/tayseer2/Weather-App",
    demo: "https://tayseer2.github.io/Weather-App/",
    description: "Fetches and displays current weather data for any location via API.",
  },
  {
    id: 9,
    title: "Prayer Times",
    cetegory: "React & Tailwindcss",
    img: "/images/main/z.png",
    giturl: "https://github.com/tayseer2/prayer-times",
    demo: "https://prayer-times-v0.netlify.app/",
    description: "Displays accurate prayer times globally, built with React and Tailwind CSS.",
  },
  {
    id: 10,
    title: "ToDo List!",
    cetegory: "React & Tailwindcss",
    img: "/images/main/c.png",
    giturl: "https://github.com/tayseer2/ToDo-List",
    demo: "https://todo-list-020.netlify.app/",
    description: "An interactive to-do list application for managing tasks, built with React.",
  },
  {
    id: 11,
    title: "My Design",
    cetegory: "React & Tailwindcss",
    img: "/images/main/v.png",
    giturl: "https://github.com/tayseer2/my-design",
    demo: "https://my-design-v2.netlify.app/",
    description: "A personal portfolio site showcasing design skills, built with React and Tailwind CSS.",
  },
  {
    id: 12,
    title: "Paint",
    cetegory: "Next & Tailwindcss",
    img: "/images/main/l.png",
    giturl: "https://github.com/tayseer-alrahhal/PAINT",
    demo: "https://paint-liard.vercel.app/",
    description: "A simple drawing application with basic paint tools, built with Next.js.",
  },
];